### ISSUE TITLE
stack trace with comment feature

### ISSUE THREAD

**Issue by alexhsamuel** [twosigma/ngrid#8]
With this csv file:

```
# comment 1
# comment 2
# comment 3
a,b,c
1,2,3
4,5,6
7,8,9
```

```
$ ngrid withcomments.csv -c '#'
Traceback (most recent call last):
  File "/Users/samuel/sw/anaconda27/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/samuel/sw/anaconda27/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/samuel/github/twosigma/ngrid/ngrid/main.py", line 129, in <module>
    main()
  File "/Users/samuel/github/twosigma/ngrid/ngrid/main.py", line 119, in main
    options.commentString, filename=filename)
  File "ngrid/grid.py", line 308, in __init__
    sample_lines, title_comments = self.__read_sample_lines(num_sample)
  File "ngrid/grid.py", line 378, in __read_sample_lines
    line = self.__read_line()
AttributeError: DelimitedFileModel instance has no attribute '_DelimitedFileModel__read_line'
```

**Comment by petr-tik** [comment]
This looks like a reasonable suggestion. Is this still open and are people interested in a PR?
